# Étape 1 : Image de base Node.js
FROM node:20

# Étape 2 : Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Étape 3 : Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier tout le code source du microservice
COPY . .

# Étape 6 : Exposer le port du microservice
EXPOSE 5001

# Étape 7 : Lancer le serveur
CMD ["node", "index.js"]
