# Étape 1 : Utiliser une image de base avec la version correcte de Go
FROM golang:1.22

# Étape 2 : Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Étape 3 : Copier les fichiers go.mod et go.sum
COPY go.mod go.sum ./

# Étape 4 : Télécharger les dépendances Go
# RUN go mod download

# Étape 5 : Copier tout le code source du microservice
COPY . .

# Étape 6 : Exposer le port
EXPOSE 5002

# Étape 7 : Lancer l'application
CMD ["go", "run", "main.go"]
