
FROM node:20

# Étape 2 : Définir le dossier de travail dans le conteneur
WORKDIR /app

# Étape 3 : Copier les fichiers de configuration
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier le reste de l’application
COPY . .

# Étape 6 : Exposer le port sur lequel ton microservice tourne
EXPOSE 5000

# Étape 7 : Démarrer l'application
CMD ["node", "index.js"]
