version: '3.9'

services:

  authentification:
    build:
      context: ./Backend/authentification
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  commandes:
    build:
      context: ./Backend/commandes
    volumes:
      - ./Backend/authentification/src/Middleware:/app/src/Middleware
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    depends_on:
      - authentification

  client:
    build:
      context: ./Frontend/myapp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - authentification
      - commandes


  Admin:
    build:
      context: ./Frontend/mon-app-angular
    ports:
      - "4200:4200"
    command: ["ng", "serve"]
    depends_on:
      - authentification
      - commandes
