# Étape 1 : Builder l'application
FROM node:20-alpine AS builder

# Dossier de travail
WORKDIR /app

# Copier les fichiers de dépendances
COPY package.json package-lock.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY . .

# Build de l'application
RUN npm run build

# Étape 2 : Image finale pour exécution
FROM node:20-alpine

# Dossier de travail
WORKDIR /app

# Copier uniquement les fichiers nécessaires à l'exécution
COPY . .

# Exposer le port utilisé par Next.js
EXPOSE 3000

# Lancer l'application Next.js en mode production
CMD ["npm", "start"]
